/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupgenerator;

import javax.swing.JOptionPane;

/**
 * Students Creation GUI
 * @author 23781271
 */
public class StudentsCreator extends javax.swing.JFrame {

    /**
     * Creates new form StudentsCreator
     */
    public StudentsCreator() {
        initComponents();
    }

    /**
     * Checks all the user input before trying to create a student: whether the
     * textFields are empty , and also for age and skillRating whether an
     * integer was input. Appropriate messages will be displayed
     * @return Returns true if all the input is correct and the student can be
     * created, returns false if some input is not correct
     */
    public boolean checkInput(){
        boolean input = false;
        if (forenameTxtField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the first name of the Student");
        }
        else if(surnameTxtField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the last name of the Student");
        }
        else {
            input = true;
        }
        return input;
    }

    /**
     * When a student is successfully created this method will clear all the 
     * input fields so it is easier to fill the information of a new student
     */
    public void clearInput(){
        forenameTxtField.setText("");
        surnameTxtField.setText("");
        ageTxtField.setText("");
        reqTxtField.setText("");
        implementationTxtField.setText("");
        documentationTxtField.setText("");
        skillsBtnGroup.clearSelection();
        reqTxtField.setEnabled(false);
        implementationTxtField.setEnabled(false);
        documentationTxtField.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        skillsBtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        forenameTxtField = new javax.swing.JTextField();
        surnameTxtField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        requirementsBtn = new javax.swing.JRadioButton();
        implementationBtn = new javax.swing.JRadioButton();
        documentationBtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        reqTxtField = new javax.swing.JTextField();
        implementationTxtField = new javax.swing.JTextField();
        documentationTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        createStudentsBtn = new javax.swing.JButton();
        showStudentsBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ageTxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Create Student");

        jLabel2.setText("Forename");

        jLabel3.setText("Surname");

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        skillsBtnGroup.add(requirementsBtn);
        requirementsBtn.setText("Requirements Gathering and Design");
        requirementsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requirementsBtnActionPerformed(evt);
            }
        });

        skillsBtnGroup.add(implementationBtn);
        implementationBtn.setText("Implementation and Testing");
        implementationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                implementationBtnActionPerformed(evt);
            }
        });

        skillsBtnGroup.add(documentationBtn);
        documentationBtn.setText("Documentation and Maintenance");
        documentationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentationBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Select Student Skill");

        reqTxtField.setEnabled(false);

        implementationTxtField.setEnabled(false);

        documentationTxtField.setEnabled(false);

        jLabel5.setText("Skill Rating");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(requirementsBtn)
                        .addComponent(implementationBtn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(documentationBtn, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reqTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(implementationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requirementsBtn)
                    .addComponent(reqTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(implementationBtn)
                    .addComponent(implementationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentationBtn)
                    .addComponent(documentationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        createStudentsBtn.setText("Create Student");
        createStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStudentsBtnActionPerformed(evt);
            }
        });

        showStudentsBtn.setText("Show Existing Students");
        showStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStudentsBtnActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Age");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(162, 162, 162))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(forenameTxtField)
                                .addGap(74, 74, 74)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(surnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(ageTxtField)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showStudentsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createStudentsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forenameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createStudentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showStudentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void showStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStudentsBtnActionPerformed
        this.dispose();
        new StudentsMenu().setVisible(true);
    }//GEN-LAST:event_showStudentsBtnActionPerformed

    private void createStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStudentsBtnActionPerformed
        if (checkInput()) {
            String firstname = forenameTxtField.getText();
            String lastname = surnameTxtField.getText();
            int age = 0;
            try {
                age = Integer.parseInt(ageTxtField.getText());
                if (requirementsBtn.isSelected()) {
                    String skill = "Requirements Gathering and Design";
                    int skillRating = 0;
                    try {
                        skillRating = Integer.parseInt(reqTxtField.getText());
                        Student newStudent = new Student(firstname, lastname, age, skill, skillRating);
                        MainMenu.groupGenerator.students.addStudent(newStudent, 1);
                        JOptionPane.showMessageDialog(null, "Student was successfully added");
                        clearInput();

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Sorry you did not input a correct skill rating, this must be a number between 1 and 10, please try again");
                        reqTxtField.setText("");
                    }

                } else if (implementationBtn.isSelected()) {
                    String skill = "Implementation and Testing";
                    int skillRating = 0;
                    try {
                        skillRating = Integer.parseInt(implementationTxtField.getText());
                        Student newStudent = new Student(firstname, lastname, age, skill, skillRating);
                        MainMenu.groupGenerator.students.addStudent(newStudent, 2);
                        JOptionPane.showMessageDialog(null, "Student was successfully added");
                        clearInput();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Sorry you did not input a correct skill rating, this must be a number between 1 and 10, please try again");
                        implementationTxtField.setText("");
                    }

                } else if (documentationBtn.isSelected()) {
                    String skill = "Documentation and Maintenance";
                    int skillRating = 0;
                    try {
                        skillRating = Integer.parseInt(documentationTxtField.getText());
                        Student newStudent = new Student(firstname, lastname, age, skill, skillRating);
                        MainMenu.groupGenerator.students.addStudent(newStudent, 3);
                        JOptionPane.showMessageDialog(null, "Student was successfully added");
                        clearInput();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Sorry you did not input a correct skill rating, this must be a number between 1 and 10, please try again");
                        documentationTxtField.setText("");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Please Select a skill");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Sorry you did not input a correct age, please try again");
                ageTxtField.setText("");
            }

        }

    }//GEN-LAST:event_createStudentsBtnActionPerformed

    private void requirementsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requirementsBtnActionPerformed
        reqTxtField.setEnabled(true);
        implementationTxtField.setEnabled(false);
        documentationTxtField.setEnabled(false);
    }//GEN-LAST:event_requirementsBtnActionPerformed

    private void implementationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_implementationBtnActionPerformed
        implementationTxtField.setEnabled(true);
        reqTxtField.setEnabled(false);
        documentationTxtField.setEnabled(false);
    }//GEN-LAST:event_implementationBtnActionPerformed

    private void documentationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentationBtnActionPerformed
        documentationTxtField.setEnabled(true);
        implementationTxtField.setEnabled(false);
        reqTxtField.setEnabled(false);
    }//GEN-LAST:event_documentationBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxtField;
    private javax.swing.JButton createStudentsBtn;
    private javax.swing.JRadioButton documentationBtn;
    private javax.swing.JTextField documentationTxtField;
    private javax.swing.JTextField forenameTxtField;
    private javax.swing.JRadioButton implementationBtn;
    private javax.swing.JTextField implementationTxtField;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField reqTxtField;
    private javax.swing.JRadioButton requirementsBtn;
    private javax.swing.JButton showStudentsBtn;
    private javax.swing.ButtonGroup skillsBtnGroup;
    private javax.swing.JTextField surnameTxtField;
    // End of variables declaration//GEN-END:variables
}
